[project]
name = "wav-to-adpcm"
version = "0.1.0"
description = "Convert WAV files to IMA ADPCM C arrays"
requires-python = ">=3.8"
dependencies = [
    "pydub>=0.25.1",
    "numpy>=1.20.0",
    "matplotlib>=3.5.0",
    "ipywidgets>=8.0.0",
    "scipy>=1.7.0",
    "jupyter>=1.1.1",
]
