[project]
name = "brain-transplant-scripts"
version = "0.1.0"
description = "Scripts for converting MIDI and audio to buzzer C code"
requires-python = ">=3.8"
dependencies = [
    "librosa>=0.10.0",
    "numpy>=1.24.0",
    "soundfile>=0.12.0",
]

[tool.uv]
package = false

