name: Build Firmware

on:
  push:
    branches: [ main ]
    paths:
      - 'SimpleSoundFirmware/**'
      - 'PolyphonicSoundFirmware/**'
      - 'Talkie/**'
      - 'SamplePlayback/**'
      - '.github/workflows/build-firmware.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'SimpleSoundFirmware/**'
      - 'PolyphonicSoundFirmware/**'
      - 'Talkie/**'
      - 'SamplePlayback/**'
      - '.github/workflows/build-firmware.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Cache PlatformIO
      uses: actions/cache@v4
      with:
        path: |
          ~/.platformio
          ~/.cache/pip
        key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}
        restore-keys: |
          ${{ runner.os }}-pio-
    
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    
    - name: Install CH32V platform
      run: pio pkg install -g -p https://github.com/Community-PIO-CH32V/platform-ch32v.git
    
    - name: Build SimpleSoundFirmware
      run: |
        cd SimpleSoundFirmware
        pio run
    
    - name: Build PolyphonicSoundFirmware
      run: |
        cd PolyphonicSoundFirmware
        pio run

    - name: Build Talkie
      run: |
        cd Talkie
        pio run

    - name: Build SamplePlayback
      run: |
        cd SamplePlayback
        pio run
