name: Build Firmware

on:
  push:
    branches: [ main ]
    paths:
      - 'firmware/**'
      - '.github/workflows/build-firmware.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'firmware/**'
      - '.github/workflows/build-firmware.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Cache PlatformIO
      uses: actions/cache@v4
      with:
        path: |
          ~/.platformio
          ~/.cache/pip
        key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}
        restore-keys: |
          ${{ runner.os }}-pio-
    
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    
    - name: Build firmware
      run: |
        cd firmware
        pio run
    
    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: firmware/.pio/build/**/*.bin
        if-no-files-found: warn

